server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # 어떤 주소로 들어오든 index.html을 바라보게 하는 핵심 설정
        try_files $uri $uri/ /index.html; 
    }
}